### ISSUE TITLE
Doubt about Ganache

### ISSUE THREAD

**Issue by enrutador** [edgefund/GeoHunter#1]
Hi
I have a question why you use ganache as a blockchain and not directly the quorum in the example? Or for architecture issues do you prefer interacting with ganache and this is synchronized with quorum blockchain?

Thanks

**Comment by GarethOates** [comment]
We used ganache as a local development blockchain so we could iterate on our solution more quickly on our own machines, without having to worry about Quorum (it was developed as part of a hackathon).  We knew that the smart contract we wrote and run against ganache would be deployable to Quorum in the end.
